# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('day', models.CharField(choices=[(b'Lunes', b'Lunes'), (b'Martes', b'Martes'), (b'Miercoles', b'Miercoles'), (b'Jueves', b'Jueves'), (b'Viernes', b'Viernes'), (b'Sabado', b'Sabado'), (b'Libre', b'Libre')], max_length=50)),
                ('dish1', models.ForeignKey(default=b'Default', on_delete=django.db.models.deletion.CASCADE, related_name='dish1', to='products.Product')),
                ('dish2', models.ForeignKey(default=b'Default', on_delete=django.db.models.deletion.CASCADE, related_name='dish2', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MenuWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=120, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='menudish',
            name='menu_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_week', to='menu.MenuWeek'),
        ),
    ]
